version: 1.0.0
title: Write a funnny poem
author:
  contact: douwe
description: a custom recipe instance from this chat session
extensions:
- type: builtin
  name: developer
  display_name: Developer
  timeout: 300
  bundled: true
settings:
  temperature: 0.0
  goose_provider: databricks
  goose_model: goose
prompt: |
  - Think of a subject
  - Create a funny poem based on that subject
  - Write the funny poem out to poem.txt
